import { create } from "@storybook/theming";
export default create({
  base: "light",
  brandTitle: "Rindu",
  brandUrl: "https://rindu.marcomadera.com",
  // brandImage: "/logo.png",
  brandTarget: "_self",
  appBg: "#fafafa",
  appContentBg: "#fafafa",
  appBorderColor: "#fafafa",
  appBorderRadius: 4,
  fontBase: "sans-serif",
  fontCode: "monospace",
  textColor: "#333",
  textInverseColor: "#fafafa",
  barTextColor: "#333",
  barSelectedColor: "#333",
  barBg: "#fafafa",
  colorPrimary: "#333",
  colorSecondary: "#333",
});
