name: Trigger Bot Response

on:
  issue_comment:
    types: [created]

jobs:
  respond_to_bot:
    uses: MarcoMadera/shared-actions/.github/workflows/bot-response.yml@main
    with:
      issue_id: ${{ github.event.issue.number }}
      base_branch: master
    secrets:
      token: ${{secrets.BOT_TOKEN}}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
