name: Publish Coverage Report

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --force

      - name: Generate coverage report
        run: npm run test:ci

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          artifact-name: github-pages
          path: coverage/lcov-report